export const data = [
  // { 
  //   id: 'string',
  //   title: 'string',
  //   description: 'string',
  //   productType: 'string',
  //   category: 'string',
  //   subcategory: 'string',
  //   regularPrice: 0,
  //   specialPrice: 0,
  //   freeShipping: false,
  //   discountOnSecondItem: false,
  //   discountOnFirstOrder: false,
  //   availableQuantity: 0,
  //   productImg: 'string'
  // },
  {
    id: 'p001',
    title: 'Whey Protein Isolate',
    description: 'High-quality whey protein isolate for muscle recovery and growth.',
    productType: 'supplement',
    category: 'proteins',
    subcategory: 'protein isolate',
    regularPrice: 49.99,
    specialPrice: 39.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 150,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'p002',
    title: 'Casein Protein',
    description: 'Slow-digesting casein protein to fuel muscles overnight.',
    productType: 'supplement',
    category: 'proteins',
    subcategory: 'protein bars',
    regularPrice: 44.99,
    specialPrice: 34.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 200,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'p003',
    title: 'Plant-Based Protein Blend',
    description: 'A complete protein source made from high-quality plant ingredients.',
    productType: 'supplement',
    category: 'proteins',
    subcategory: 'blended protein mixes',
    regularPrice: 39.99,
    specialPrice: 29.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 100,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'p004',
    title: 'Hydrolyzed Whey Protein',
    description: 'Advanced hydrolyzed whey protein for faster absorption and muscle recovery.',
    productType: 'supplement',
    category: 'proteins',
    subcategory: 'protein concentrates',
    regularPrice: 59.99,
    specialPrice: 49.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: false,
    availableQuantity: 75,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'fb001',
    title: 'Thermogenic Fat Burner',
    description: 'Boost your metabolism and burn fat with our powerful thermogenic formula.',
    productType: 'supplement',
    category: 'fat burners',
    subcategory: 'thermogenic supplements',
    regularPrice: 29.99,
    specialPrice: 24.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 120,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'fb002',
    title: 'Green Tea Extract',
    description: 'Natural fat burner with green tea extract for enhanced weight loss.',
    productType: 'supplement',
    category: 'fat burners',
    subcategory: 'herbal and extract-based fat bureners',
    regularPrice: 19.99,
    specialPrice: 15.99,
    freeShipping: false,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 200,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'fb003',
    title: 'CLA (Conjugated Linoleic Acid)',
    description: 'Support your weight loss goals with CLA, a natural fat burner.',
    productType: 'supplement',
    category: 'fat burners',
    subcategory: 'metabolistm-boosting complexes',
    regularPrice: 25.99,
    specialPrice: 20.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 150,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'fb004',
    title: 'L-Carnitine Liquid',
    description: 'Enhance your fat metabolism and energy levels with L-Carnitine liquid.',
    productType: 'supplement',
    category: 'fat burners',
    subcategory: 'fat burners for women',
    regularPrice: 34.99,
    specialPrice: 29.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: false,
    availableQuantity: 80,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'bcaa001',
    title: 'BCAA Powder',
    description: 'Premium BCAA powder for muscle recovery and endurance.',
    productType: 'supplement',
    category: 'BCAA',
    subcategory: 'Pure BCAA powder',
    regularPrice: 29.99,
    specialPrice: 24.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 100,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'bcaa002',
    title: 'BCAA Capsules',
    description: 'Convenient BCAA capsules for on-the-go muscle support.',
    productType: 'supplement',
    category: 'BCAA',
    subcategory: 'BCAA in capsules',
    regularPrice: 34.99,
    specialPrice: 29.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 150,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'bcaa003',
    title: 'BCAA Energy Drink',
    description: 'Refreshing BCAA energy drink for workout performance and recovery.',
    productType: 'supplement',
    category: 'BCAA',
    subcategory: 'BCAA conmplex with additives',
    regularPrice: 19.99,
    specialPrice: 15.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: false,
    availableQuantity: 200,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'bcaa004',
    title: 'BCAA Tablets',
    description: 'High-potency BCAA tablets for muscle building and recovery.',
    productType: 'supplement',
    category: 'BCAA',
    subcategory: 'BCAA blends for recovery',
    regularPrice: 39.99,
    specialPrice: 34.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 80,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'g001',
    title: 'Mass Gainer Powder',
    description: 'High-calorie mass gainer powder for bulking and muscle growth.',
    productType: 'supplement',
    category: 'gainers',
    subcategory: 'mass gainer',
    regularPrice: 49.99,
    specialPrice: 44.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 120,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'g002',
    title: 'Weight Gainer Shake',
    description: 'Nutrient-rich weight gainer shake to help you reach your calorie goals.',
    productType: 'supplement',
    category: 'gainers',
    subcategory: 'gainers with creatine',
    regularPrice: 39.99,
    specialPrice: 34.99,
    freeShipping: false,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 150,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'g003',
    title: 'High-Calorie Gainer',
    description: 'Packed with protein and carbs, this gainer helps you bulk up quickly.',
    productType: 'supplement',
    category: 'gainers',
    subcategory: 'high-carb gainer complexes',
    regularPrice: 54.99,
    specialPrice: 49.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 90,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'g004',
    title: 'Lean Mass Gainer',
    description: 'Supports lean muscle growth with a balanced nutrient profile.',
    productType: 'supplement',
    category: 'gainers',
    subcategory: 'protein gainers',
    regularPrice: 44.99,
    specialPrice: 39.99,
    freeShipping: false,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 200,
    productImg: '../assets/images/supplement-2.png'
  }
]