export const data = [
  // { 
  //   id: 'string',
  //   title: 'string',
  //   description: 'string',
  //   productType: 'string',
  //   category: 'string',
  //   subcategory: 'string',
  //   regularPrice: 0,
  //   specialPrice: 0,
  //   freeShipping: false,
  //   discountOnSecondItem: false,
  //   discountOnFirstOrder: false,
  //   availableQuantity: 0,
  //   productImg: 'string'
  // },
  {
    id: 'p001',
    title: 'Whey Protein Isolate',
    description: 'High-quality whey protein isolate for muscle recovery and growth.',
    productType: 'supplement',
    category: 'proteins',
    subcategory: 'protein isolate',
    regularPrice: 49.99,
    specialPrice: 39.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 150,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'p002',
    title: 'Casein Protein',
    description: 'Slow-digesting casein protein to fuel muscles overnight.',
    productType: 'supplement',
    category: 'proteins',
    subcategory: 'protein bars',
    regularPrice: 44.99,
    specialPrice: 34.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 200,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'p003',
    title: 'Plant-Based Protein Blend',
    description: 'A complete protein source made from high-quality plant ingredients.',
    productType: 'supplement',
    category: 'proteins',
    subcategory: 'blended protein mixes',
    regularPrice: 39.99,
    specialPrice: 29.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 100,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'p004',
    title: 'Hydrolyzed Whey Protein',
    description: 'Advanced hydrolyzed whey protein for faster absorption and muscle recovery.',
    productType: 'supplement',
    category: 'proteins',
    subcategory: 'protein concentrates',
    regularPrice: 59.99,
    specialPrice: 49.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: false,
    availableQuantity: 75,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'fb001',
    title: 'Thermogenic Fat Burner',
    description: 'Boost your metabolism and burn fat with our powerful thermogenic formula.',
    productType: 'supplement',
    category: 'fat burners',
    subcategory: 'thermogenic supplements',
    regularPrice: 29.99,
    specialPrice: 24.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 120,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'fb002',
    title: 'Green Tea Extract',
    description: 'Natural fat burner with green tea extract for enhanced weight loss.',
    productType: 'supplement',
    category: 'fat burners',
    subcategory: 'herbal and extract-based fat bureners',
    regularPrice: 19.99,
    specialPrice: 15.99,
    freeShipping: false,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 200,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'fb003',
    title: 'CLA (Conjugated Linoleic Acid)',
    description: 'Support your weight loss goals with CLA, a natural fat burner.',
    productType: 'supplement',
    category: 'fat burners',
    subcategory: 'metabolistm-boosting complexes',
    regularPrice: 25.99,
    specialPrice: 20.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 150,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'fb004',
    title: 'L-Carnitine Liquid',
    description: 'Enhance your fat metabolism and energy levels with L-Carnitine liquid.',
    productType: 'supplement',
    category: 'fat burners',
    subcategory: 'fat burners for women',
    regularPrice: 34.99,
    specialPrice: 29.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: false,
    availableQuantity: 80,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'bcaa001',
    title: 'BCAA Powder',
    description: 'Premium BCAA powder for muscle recovery and endurance.',
    productType: 'supplement',
    category: 'BCAA',
    subcategory: 'Pure BCAA powder',
    regularPrice: 29.99,
    specialPrice: 24.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 100,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'bcaa002',
    title: 'BCAA Capsules',
    description: 'Convenient BCAA capsules for on-the-go muscle support.',
    productType: 'supplement',
    category: 'BCAA',
    subcategory: 'BCAA in capsules',
    regularPrice: 34.99,
    specialPrice: 29.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 150,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'bcaa003',
    title: 'BCAA Energy Drink',
    description: 'Refreshing BCAA energy drink for workout performance and recovery.',
    productType: 'supplement',
    category: 'BCAA',
    subcategory: 'BCAA conmplex with additives',
    regularPrice: 19.99,
    specialPrice: 15.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: false,
    availableQuantity: 200,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'bcaa004',
    title: 'BCAA Tablets',
    description: 'High-potency BCAA tablets for muscle building and recovery.',
    productType: 'supplement',
    category: 'BCAA',
    subcategory: 'BCAA blends for recovery',
    regularPrice: 39.99,
    specialPrice: 34.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 80,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'g001',
    title: 'Mass Gainer Powder',
    description: 'High-calorie mass gainer powder for bulking and muscle growth.',
    productType: 'supplement',
    category: 'gainers',
    subcategory: 'mass gainer',
    regularPrice: 49.99,
    specialPrice: 44.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 120,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'g002',
    title: 'Weight Gainer Shake',
    description: 'Nutrient-rich weight gainer shake to help you reach your calorie goals.',
    productType: 'supplement',
    category: 'gainers',
    subcategory: 'gainers with creatine',
    regularPrice: 39.99,
    specialPrice: 34.99,
    freeShipping: false,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 150,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'g003',
    title: 'High-Calorie Gainer',
    description: 'Packed with protein and carbs, this gainer helps you bulk up quickly.',
    productType: 'supplement',
    category: 'gainers',
    subcategory: 'high-carb gainer complexes',
    regularPrice: 54.99,
    specialPrice: 49.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 90,
    productImg: '../assets/images/supplement-1.png'
  },
  {
    id: 'g004',
    title: 'Lean Mass Gainer',
    description: 'Supports lean muscle growth with a balanced nutrient profile.',
    productType: 'supplement',
    category: 'gainers',
    subcategory: 'protein gainers',
    regularPrice: 44.99,
    specialPrice: 39.99,
    freeShipping: false,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 200,
    productImg: '../assets/images/supplement-2.png'
  },
  {
    id: 'db001',
    title: 'Adjustable Dumbbells Set',
    description: 'A versatile set of adjustable dumbbells for a customizable workout.',
    productType: 'sporting goods',
    category: 'dumbbells and barbells',
    subcategory: 'dumbbells',
    regularPrice: 99.99,
    specialPrice: 79.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 50,
    productImg: '../assets/images/dumbbells-black.png'
  },
  {
    id: 'bb001',
    title: 'Olympic Barbell',
    description: 'High-quality Olympic barbell designed for heavy lifting and durability.',
    productType: 'sporting goods',
    category: 'dumbbells and barbells',
    subcategory: 'barbells',
    regularPrice: 199.99,
    specialPrice: 179.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 30,
    productImg: '../assets/images/dumbbells-black.png'
  },
  {
    id: 'db002',
    title: 'Neoprene Dumbbells Set',
    description: 'A set of neoprene-coated dumbbells for a comfortable and secure grip.',
    productType: 'sporting goods',
    category: 'dumbbells and barbells',
    subcategory: 'dumbbells',
    regularPrice: 49.99,
    specialPrice: 39.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 100,
    productImg: '../assets/images/dumbbells-green.png'
  },
  {
    id: 'bb002',
    title: 'Hex Trap Bar',
    description: 'A hex trap bar for deadlifts, shrugs, and farmer’s walks, promoting better form and reduced strain.',
    productType: 'sporting goods',
    category: 'dumbbells and barbells',
    subcategory: 'barbells',
    regularPrice: 149.99,
    specialPrice: 129.99,
    freeShipping: false,
    discountOnSecondItem: false,
    discountOnFirstOrder: false,
    availableQuantity: 25,
    productImg: '../assets/images/dumbbells-black.png'
  },
  {
    id: 'fe001',
    title: 'Treadmill',
    description: 'High-performance treadmill with multiple workout programs and incline settings.',
    productType: 'sporting goods',
    category: 'fitness equipment',
    subcategory: 'cardio equipment',
    regularPrice: 899.99,
    specialPrice: 749.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 20,
    productImg: '../assets/images/dumbbells-black.png'
  },
  {
    id: 'fe002',
    title: 'Yoga Mat',
    description: 'Non-slip yoga mat with extra cushioning for superior comfort and support.',
    productType: 'sporting goods',
    category: 'fitness equipment',
    subcategory: 'yoga and pilates',
    regularPrice: 29.99,
    specialPrice: 19.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 150,
    productImg: '../assets/images/dumbbells-green.png'
  },
  {
    id: 'fe003',
    title: 'Adjustable Kettlebell',
    description: 'Adjustable kettlebell with multiple weight settings for versatile workouts.',
    productType: 'sporting goods',
    category: 'fitness equipment',
    subcategory: 'strength training',
    regularPrice: 79.99,
    specialPrice: 69.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 50,
    productImg: '../assets/images/dumbbells-green.png'
  },
  {
    id: 'fe004',
    title: 'Resistance Bands Set',
    description: 'Set of resistance bands with varying levels of resistance for full-body workouts.',
    productType: 'sporting goods',
    category: 'fitness equipment',
    subcategory: 'strength training',
    regularPrice: 49.99,
    specialPrice: 39.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 200,
    productImg: '../assets/images/dumbbells-black.png'
  },
  {
    id: 'cw001',
    title: 'Stationary Bike',
    description: 'High-quality stationary bike with adjustable resistance levels and a digital display.',
    productType: 'sporting goods',
    category: 'cardio workouts',
    subcategory: 'stationary bikes',
    regularPrice: 499.99,
    specialPrice: 449.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 30,
    productImg: '../assets/images/dumbbells-black.png'
  },
  {
    id: 'cw002',
    title: 'Rowing Machine',
    description: 'Durable rowing machine with smooth rowing action and multiple resistance settings.',
    productType: 'sporting goods',
    category: 'cardio workouts',
    subcategory: 'rowing machines',
    regularPrice: 699.99,
    specialPrice: 649.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: false,
    availableQuantity: 20,
    productImg: '../assets/images/dumbbells-black.png'
  },
  {
    id: 'cw003',
    title: 'Elliptical Trainer',
    description: 'Compact elliptical trainer with variable resistance and built-in workout programs.',
    productType: 'sporting goods',
    category: 'cardio workouts',
    subcategory: 'elliptical trainers',
    regularPrice: 599.99,
    specialPrice: 549.99,
    freeShipping: true,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 40,
    productImg: '../assets/images/dumbbells-green.png'
  },
  {
    id: 'cw004',
    title: 'Jump Rope',
    description: 'Durable jump rope with comfortable handles and adjustable length for a full-body cardio workout.',
    productType: 'sporting goods',
    category: 'cardio workouts',
    subcategory: 'jump ropes',
    regularPrice: 19.99,
    specialPrice: 14.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: true,
    availableQuantity: 200,
    productImg: '../assets/images/dumbbells-green.png'
  },
  {
    id: 'sa001',
    title: 'Fitness Tracker',
    description: 'Advanced fitness tracker with heart rate monitoring, step counting, and sleep tracking.',
    productType: 'sporting goods',
    category: 'sport accessories',
    subcategory: 'wearables',
    regularPrice: 99.99,
    specialPrice: 89.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 100,
    productImg: '../assets/images/dumbbells-green.png'
  },
  {
    id: 'sa002',
    title: 'Water Bottle',
    description: 'BPA-free water bottle with a leak-proof lid and time marker for daily hydration goals.',
    productType: 'sporting goods',
    category: 'sport accessories',
    subcategory: 'hydration',
    regularPrice: 19.99,
    specialPrice: 14.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 500,
    productImg: '../assets/images/dumbbells-green.png'
  },
  {
    id: 'sa003',
    title: 'Gym Bag',
    description: 'Spacious and durable gym bag with multiple compartments and a shoe pocket.',
    productType: 'sporting goods',
    category: 'sport accessories',
    subcategory: 'bags',
    regularPrice: 49.99,
    specialPrice: 39.99,
    freeShipping: true,
    discountOnSecondItem: false,
    discountOnFirstOrder: true,
    availableQuantity: 200,
    productImg: '../assets/images/dumbbells-black.png'
  },
  {
    id: 'sa004',
    title: 'Sweatband Set',
    description: 'Comfortable and absorbent sweatband set including headband and wristbands.',
    productType: 'sporting goods',
    category: 'sport accessories',
    subcategory: 'wearables',
    regularPrice: 14.99,
    specialPrice: 9.99,
    freeShipping: false,
    discountOnSecondItem: true,
    discountOnFirstOrder: false,
    availableQuantity: 300,
    productImg: '../assets/images/dumbbells-black.png'
  }
]